### ISSUE TITLE
Results look different when displayed in Google Colab

### ISSUE THREAD

**Issue by woctezuma** [aminnj/tidfit#1]
When running the examples in Google Colab, the results are displayed differently from the results shown in the README.

```bash
%pip install tidfit
```
```
Collecting tidfit
  Downloading tidfit-0.2.0-py3-none-any.whl (4.4 kB)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from tidfit) (3.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from tidfit) (1.4.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from tidfit) (1.19.5)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->tidfit) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->tidfit) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->tidfit) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->tidfit) (2.4.7)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from cycler>=0.10->matplotlib->tidfit) (1.15.0)
Installing collected packages: tidfit
Successfully installed tidfit-0.2.0
```

Then:

![Example 1](https://i.imgur.com/KkovBzo.png)

![Example 2](https://i.imgur.com/RyeDQZx.png)

![Example 3](https://i.imgur.com/serlWYV.png)

![Example 4](https://i.imgur.com/krj00AG.png)

**Comment by aminnj** [comment]
Thanks for reporting. 

Looks like when combined into the same cell, your first two screenshots would match the first plot of the readme. But apparently `scipy.optimize.curve_fit` is very sensitive to the data in the next two plots. Can you try to insert
```python
np.random.seed(8)
```
at the beginning of your third screenshot?

**Comment by woctezuma** [comment]
> 
> Looks like when combined into the same cell, your first two screenshots would match the first plot of the readme.

Correct.

![Combined cells](https://i.imgur.com/X68ycRi.png)

Similarly, for the last plot, I need to run `subplots()` and `errorbar()` again in order to superimpose the data points and the curve:

```python
fig, ax = plt.subplots()
ax.errorbar(x, y, yerr=y**0.5, fmt="o", ms=5)
```

![Last plot](https://i.imgur.com/awS6NY6.png)

>
> But apparently `scipy.optimize.curve_fit` is very sensitive to the data in the next two plots. Can you try to insert
> 
> ```python
> np.random.seed(8)
> ```
> 
> at the beginning of your third screenshot?

Correct. This fixes the plot.

![Fixed plot](https://i.imgur.com/fxzcOnW.png)

However, the legend overlaps with the curves, which does not happen in the README.
Is there a way to fix the display of the legend, or force it to be positioned elsewhere, e.g. with a function argument?
Or did you manually move the legend for the README?

**Comment by aminnj** [comment]
I left the matplotlib tweaks out of the readme. You can prevent the legend from overlapping with
```python
fig, ax = plt.subplots()
# rest of code
ax.legend(ncol=2)
ax.set_ylim([0, 100])
```
which increases the y-limit to make room for the legend and uses two columns.

**Comment by woctezuma** [comment]
Perfect! Thank you!

```python
ax.legend(ncol=2)
ax.set_ylim([0, 110])
```
![Perfect plot](https://i.imgur.com/uaPlZrd.png)

```python
ax.set_ylim([0, 150])
```
![Second perfect plot](https://i.imgur.com/iKRoQzK.png)

**Comment by aminnj** [comment]
No problem :)
